### ISSUE TITLE
Incompatible with 1.1

### ISSUE THREAD

**Issue by moronic** [comwes/mkpdfs-mkdocs-plugin#23]
With mkdocs 1.1 and material 5.1.7, can't render pdfs, I get

/python3.8/site-packages/mkpdfs_mkdocs/mkpdfs.py", line 20, in Mkpdfs ('design', config_options.Type(utils.string_types, default=None)),

AttributeError: module 'mkdocs.utils' has no attribute 'string_types'

I assume it is this same problem: 
https://github.com/zhaoterryy/mkdocs-pdf-export-plugin/commit/7c6c82c96490a84b4bd617e21977259f60dd5007

**Comment by jwaschkau** [comment]
Hi Moronic,

see #15

**Comment by trogper** [comment]
This should already be fixed in git, but is not yet released on pypi.  
I suggest you to try the newest code from git and close the issue

**Comment by markvincze** [comment]
Hey @comwes,

Are you planning to do a new release in the near future so that this fix would be rolled out?

**Comment by moronic** [comment]
Why does install from git count as a solved issue?

**Comment by jollyparamjit** [comment]
I am using mkdocs==1.1.2 & mkdocs-material 5.3.0 for my project.

mkdocs-material 5.3.0 has requirement mkdocs>=1.1, but you'll have mkdocs 1.0.4 which is incompatible.

Can you help, how do i keep mkdocs 1.1.2 & this pdf plugin.

**Comment by jwaschkau** [comment]
> 
> 
> I am using mkdocs==1.1.2 & mkdocs-material 5.3.0 for my project.
> 
> mkdocs-material 5.3.0 has requirement mkdocs>=1.1, but you'll have mkdocs 1.0.4 which is incompatible.
> 
> Can you help, how do i keep mkdocs 1.1.2 & this pdf plugin.

Hi,

you can install from my repository until the PR`s are merged. It works with mkdocs >=1.1 and i tested it with mkdocs-material 5.3.2.

`https://github.com/jwaschkau/mkpdfs-mkdocs-plugin.git#egg=mkpdfs-mkdocs-plugin`

**Comment by vasicvuk** [comment]
When will this fix be released?

**Comment by Deastrom** [comment]
Can we please get this released.  Not having good luck with a competing plugin and would like to see how this one works.

or please provide instructions on how to install this plugin outside of pip.

**Comment by trogper** [comment]
> Can we please get this released. Not having good luck with a competing plugin and would like to see how this one works.
> 
> or please provide instructions on how to install this plugin outside of pip.

`pip install git+https://github.com/jwaschkau/mkpdfs-mkdocs-plugin.git#egg=mkpdfs-mkdocs-plugin`

**Comment by fletort** [comment]
> @Deastrom
> 
> > Can we please get this released. Not having good luck with a competing plugin and would like to see how this one works.
> > or please provide instructions on how to install this plugin outside of pip.
> 
> `pip install git+https://github.com/jwaschkau/mkpdfs-mkdocs-plugin.git#egg=mkpdfs-mkdocs-plugin`

WIth this method you have now the bug #19 :-)

**Comment by Deastrom** [comment]
Yeah... I'm playing with Dita now

**Comment by trogper** [comment]
you can pull the css from official pypi package and put it into the git-installed one, that should help

**Comment by comwes** [comment]
Issue will be fixed in the upcoming relaase
